---
title: "CANDEV employee retention wip"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

# load package and install if package is not found
pkg <- c("data.table", "dplyr", "ggcorrplot", "reshape", "ggpubr")

for (i in pkg) {
  if (pkg %in% installed.packages()[, "Package"] == FALSE) {
    install.package(i)
  } else {
    library(i, character.only = TRUE)
  }
}

#load data from url
data <- fread("https://open.canada.ca/data/dataset/4301f4bb-1daa-4b50-afab-d1193b5d2284/resource/63f972a8-8bf2-4584-a735-e5d0c07a9eb6/download/subset-3-sous-ensemble-3.csv")
```

```{r}
# filter by select subcategory indicating racism, discrimination, inclusion, empowerment, etc.
# several irrelevant columns were also removed 
data_ISED <- data %>% filter(DEPT_E == "Innovation, Science and Economic Development Canada")

#  remove NA
data_ISED <- data_ISED %>% filter(complete.cases(data_ISED))
data <- data %>% filter(complete.cases(data))

# various demographic groups' response to questions related to racism 
data_racism <- data %>% filter(QUESTION %in% c("Q23", "Q47", "Q48", "Q67", "Q68")) %>%
  group_by(DESCRIP_E) %>% summarise(avg_agree = mean(AGREE))
ISED_racism <- data_ISED %>% filter(QUESTION %in% c("Q23", "Q47", "Q48", "Q67", "Q68")) %>%
  group_by(DESCRIP_E) %>% summarise(avg_agree = mean(AGREE))

# demographic groups' response to questions related to diversity
data_diversity <- data %>% filter(QUESTION %in% c("Q46", "Q20", "Q45", "Q79e","Q2")) %>%
  group_by(DESCRIP_E) %>% summarise(avg_agree = mean(AGREE))
ISED_diversity <- data_ISED %>% filter(QUESTION %in% c("Q46", "Q20", "Q45", "Q79e","Q2")) %>%
  group_by(DESCRIP_E) %>% summarise(avg_agree = mean(AGREE))

# demographic groups' response to questions related to ethics at workplace
data_ethics <- data %>% filter(QUESTION %in% c("Q21", "Q22", "Q31", "Q38", "Q39", "Q61")) %>%
  group_by(DESCRIP_E) %>% summarise(avg_agree = mean(AGREE))
ISED_ethics <- data_ISED %>% filter(QUESTION %in% c("Q21", "Q22", "Q31", "Q38", "Q39", "Q61")) %>%
  group_by(DESCRIP_E) %>% summarise(avg_agree = mean(AGREE))

# demographic groups' satisfaction at work
data_satisfaction <- data %>% filter(QUESTION %in% c("Q07", "Q08", "Q11", "Q16","Q30", "Q51", "Q50")) %>%
  group_by(DESCRIP_E) %>% summarise(avg_agree = mean(AGREE))

#demographic groups' development at work
data_developement <- data %>% filter(QUESTION %in% c("Q13", "Q26", "Q24", "Q27","Q42")) %>%
  group_by(DESCRIP_E) %>% summarise(avg_agree = mean(AGREE))
ISED_developement <- data_ISED %>% filter(QUESTION %in% c("Q13", "Q26", "Q24", "Q27","Q42")) %>%
  group_by(DESCRIP_E) %>% summarise(avg_agree = mean(AGREE))

# join to a single table
data_new <- left_join(data_racism, data_diversity, by = "DESCRIP_E") %>% 
  left_join(., data_ethics, by = "DESCRIP_E") %>% 
  left_join(., data_satisfaction, by = "DESCRIP_E") %>%
  left_join(., data_developement, by = "DESCRIP_E")

ISED_new <- left_join(ISED_racism, ISED_diversity, by = "DESCRIP_E") %>% 
  left_join(., ISED_ethics, by = "DESCRIP_E") %>% 
  left_join(., ISED_developement, by = "DESCRIP_E")

# rename columns
colnames(data_new) <- c("demographic", "racism", "diversity", "satisfaction", "ethics", "development")
colnames(ISED_new) <- c("demographic", "racism", "diversity", "ethics", "development")

# removes demographic containing "Not selected"
data_new <- data_new %>% filter(!grepl("Not selected", demographic))
ISED_new <- ISED_new %>% filter(!grepl("Not selected", demographic))

# still need to add accessibility/age/sexism/desire to leave/harassment factors

```

```{r}
# shorter label given for demographic for visualization purposes
relabel <- c("A chronic health condition",  
             "A cognitive disability", 
             "A hearing disability", 
             "A mental health issue",
             "A mobility issue", 
             "A seeing disability", 
             "A sensory / environmental disability", 
             "An intellectual disability", 
             "An issue with flexibility or dexterity",
             "Another sexual orientation", "Bisexual",
             "Black", "Chinese", "Female gender", "Filipino",
             "First Nation (North American Indian)", "Gay or lesbian", 
             "Gender diverse", "Heterosexual", "Indigenous", 
             "Inuk (Inuit)", "Japanese", "Korean", "Male gender", "Métis",
             "Non-Indigenous", "Non-visible minority", "Non-White Latin American", 
             "Non-White West Asian, North African or Arab ", 
             "Not a person with a disability", "Other disability", 
             "Other visible minority group", "Person of mixed origin", 
             "Person with a disability", "Prefer not to answer", 
             "South Asian/East Indian", "Southeast Asian", "Visible minority")
relabel_ISED <- c("A chronic health condition",  
             "A cognitive disability", 
             "A hearing disability", 
             "A mental health issue",
             "A mobility issue", 
             "A seeing disability", 
             "A sensory / environmental disability", 
             "An issue with flexibility or dexterity",
             "Another sexual orientation", "Bisexual",
             "Black", "Chinese", "Female gender", "Filipino",
             "First Nation (North American Indian)", "Gay or lesbian", 
             "Gender diverse", "Heterosexual", "Indigenous", 
             "Male gender", "Métis",
             "Non-Indigenous", "Non-visible minority", "Non-White Latin American", 
             "Non-White West Asian, North African or Arab ", 
             "Not a person with a disability", "Other disability", 
             "Other visible minority group", "Person of mixed origin", 
             "Person with a disability", "Prefer not to answer", 
             "South Asian/East Indian", "Southeast Asian", "Visible minority")
data_new$demographic <- relabel
ISED_new$demographic <- relabel_ISED

# heat map for all dept
data_heatmap <- melt(setDT(data_new, keep.rownames = TRUE), "demographic")
data_heatmap[-c(1:38),] %>% ggplot(aes(x = demographic, y = variable, fill = as.integer(value))) + 
  geom_tile() + scale_fill_gradient(low = "#f8d9f9", high = "#60006d" ) + coord_flip() + 
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold"),
    panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank(),
    panel.background = element_blank()
  ) + labs(title = "Average % of Positive Response for All", x = "Factors of Interest", 
           y = "Demographic") + guides(fill = guide_legend(title = "% of Positive Response")) 

# heat map for ISED dept
ISED_heatmap <- melt(setDT(ISED_new, keep.rownames = TRUE), "demographic")
ISED_heatmap[-c(1:38),] %>% ggplot(aes(x = demographic, y = variable, fill = as.integer(value))) + 
  geom_tile() + scale_fill_gradient(low = "#f8d9f9", high = "#60006d" ) + coord_flip() + 
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold"),
    panel.grid.major = element_blank(), 
    panel.grid.minor = element_blank(),
    panel.background = element_blank()
  ) + labs(title = "Average % of Positive Response within ISED", x = "Factors of Interest", 
           y = "Demographic") + guides(fill = guide_legend(title = "% of Positive Response")) 

#correlation plot 
correlation_plot <- cor(data_new[,-c(1,2)])
ggcorrplot(correlation_plot, hc.order = TRUE, type = "lower", outline.col = "white") + theme_dark() + 
  scale_x_discrete(guide = guide_axis(angle = 90)) + theme(
    plot.title = element_text(hjust = 0.5, face = "bold"),
    axis.title.x = element_blank(),
    axis.title.y = element_blank()
  ) + labs(title = "Correlation Matrix for All") + 
  guides(fill = guide_legend(title = "correlation"))

correlation_plot <- cor(ISED_new[,-c(1,2)])
ggcorrplot(correlation_plot, hc.order = TRUE, type = "lower", outline.col = "white") + theme_dark() + 
  scale_x_discrete(guide = guide_axis(angle = 90)) + theme(
    plot.title = element_text(hjust = 0.5, face = "bold"),
    axis.title.x = element_blank(),
    axis.title.y = element_blank()
  ) + labs(title = "Correlation Matrix for ISED") + 
  guides(fill = guide_legend(title = "correlation"))
```

```{r}
# Importing the subset data csv file that was given:
candev_2022_data <- data

# Determining the number of rows in the data set
nrow(candev_2022_data) #1405579


# Number of variables from the data set:
ncol(candev_2022_data) #35


# Number of variables in the data set:
names(candev_2022_data)

# Variables with their class too in the data set:
str(candev_2022_data)

# Determining number of variables in the datasheet
length(colnames(candev_2022_data))
 
head(candev_2022_data)


# Sub-setting the data into "Innovation, Science and Economic Development Canada"
data_ISED <- candev_2022_data %>% 
  filter(DEPT_E == "Innovation, Science and Economic Development Canada")

#Determining the number of rows for data_ISED
nrow(data_ISED) #21782

# To determine the number of "Na" for each column number
data_ISED %>% 
  summarise_all((~ sum(is.na(.)))) #9401

#9401 / nrow(data_ISED) #21782 = 0.4315949


# Outputs for different variables 
unique(data_ISED$LEVEL1ID) #10

unique(data_ISED$LEVEL2ID) #0


unique(data_ISED$LEVEL3ID) #0


unique(data_ISED$LEVEL4ID) #0


unique(data_ISED$LEVEL5ID) #0


unique(data_ISED$SURVEYR) # 2020, 2019, 2018

unique(data_ISED$BYCOND) #
unique(data_ISED$DESCRIP_E) # {male, female, gender diverese, Indigenous, Non-Indigenous, First Nation, Metis, Inuk, Person with a disability, specific disability, mental health, intellectual abilities, sensory/environmental disability, visible minority [32], black [33], black - Not selected [34], chinese [35], filipino [37], Japanese [39], Korean [41,], South Asian/East Indian, Southeast Asian, Non-White west Asian, North African or Arab, Non-White Latin American, Person of mixed origin, Other visible minority group, "Heterosexual", "gay or lesbian", "bisexual", "another sexual orientation", }

unique(data_ISED$DEMCODE) #[2011, 2069]

unique(data_ISED$QUESTION) #[Q01, Q97]

unique(data_ISED$TITLE_E) #[Question 1, Question 97]

unique(data_ISED$ANSWER1) #[0, 100]
unique(data_ISED$ANSWER2) #[0, 100]
unique(data_ISED$ANSWER3) #[0, 9999]
unique(data_ISED$ANSWER4) #[0, 9999]
unique(data_ISED$ANSWER5) #[0, 9999]
unique(data_ISED$ANSWER6) #[0, 9999]
unique(data_ISED$ANSWER7) #[0,9999]
unique(data_ISED$MOST_POSITIVE_OR_LEAST_NEGATIVE) #[0, 9999]
unique(data_ISED$NEUTRAL_OR_MIDDLE_CATEGORY) #[0, 9999]
unique(data_ISED$MOST_NEGATIVE_OR_LEAST_POSITIVE) #[0, 9999]
unique(data_ISED$AGREE) #[0, 9999]
unique(data_ISED$SCORE5) #[1.51, 99.00]
unique(data_ISED$SCORE100) #[13, 9999]
unique(data_ISED$ANSCOUNT) #[10, 3690]
unique(data_ISED$DEPT_E) #"Innovation, Science and Economic Development Canada"
unique(data_ISED$DEPT_F) #GET RID OF THIS VARIABLE
unique(data_ISED$INDICATORID) #[1, 6]
unique(data_ISED$INDICATORENG) # "workplace", "Workforce", "Leadership", "Workplace Well-Being", "Employee Engagement", "Compensation"
unique(data_ISED$SUBINDICATORID) #[1, 23]
unique(data_ISED$SUBINDICATORENG) #Categories such as organizational goals, mobility and retention, harassment
```

```{r}
# Sub-setting the data to get rid of the N.A's
candev_data <- na.omit(data_ISED)

#update on the number of rows:
nrow(candev_data) #12381


nrow(candev_data) / nrow(data_ISED) #0.5684051
#this indicates we need to replace the N.A's with medians

nrow(candev_data) / nrow(candev_2022_data) #0.00880847

# Sub-setting the data to exclude responses that have "9999"

#candev_data_2 <- subset(candev_data, ANSWER3 != "9999", ANSWER4 != "9999", 
                        #ANSWER5 != "9999", ANSWER6 != "9999", ANSWER7 != "9999", 
                        #AGREE != "9999", SCORE100 != "9999")

candev_data_2 <- subset(candev_data, ANSWER3 != "9999" & ANSWER4 != "9999" & ANSWER5 != "9999" & ANSWER6 != "9999" & ANSWER7 != "9999" & AGREE != "9999" & SCORE100 != "9999")

nrow(candev_data_2) #9427

nrow(candev_data_2) / nrow(data_ISED) #0.4327885

nrow(candev_data_2) / nrow(candev_2022_data) # 0.006706845


#Sub-setting the data to get rid of Level2ID, Level3ID, Level3ID, Level5ID
candev_data_2 <- subset(candev_data_2, select=-c(LEVEL2ID, LEVEL3ID, LEVEL4ID, LEVEL5ID))
```


```{r}
#SAMPLE CREATING A TRAINING SET, TESTING SET, AND VALIDATION SET:
# Step 1: defining the data set

#candev_data_2

# Step 2: Setting the fractions of the data frame that I want to split into training, validation and test

Training_percentage <- 0.70
Validation_percentage <- 0.15
Testing_percentage <- 0.15

# Computing Sample sizes

Training_sample_size <- floor(Training_percentage * nrow(candev_data_2)) 
Validation_sample_size <- floor(Validation_percentage * nrow(candev_data_2))
Testing_sample_size <- floor(Testing_percentage * nrow(candev_data_2))

# Create the randomly-sampled indices for the data frame. Use setdiff() to avoid overlapping subsets of indices.

Training_indices <- sort(sample(seq_len(nrow(candev_data_2)), size=Training_sample_size))
Non_training_indices <- setdiff(seq_len(nrow(candev_data_2)), Training_indices)
Validation_indices <- sort(sample(Non_training_indices, size=Validation_sample_size))
Testing_indices <- setdiff(Non_training_indices, Validation_indices)


#Outputting the three different data frames

Training_dataframe   <- candev_data_2[Training_indices, ]
Validation_dataframe <- candev_data_2[Validation_indices, ]
Testing_dataframe <- candev_data_2[Testing_indices, ]



nrow(Training_dataframe)
#6757, approx. 69.990%
nrow(Validation_dataframe)
#1447, apporx. 14.99%
nrow(Testing_dataframe)
#1449, approx. 15.01%

```

```{r}

ggplot(Training_dataframe) +
  geom_histogram(aes(x = DEMCODE, y = ..density..))




ggplot(Training_dataframe, aes(x = DEMCODE)) +
  geom_histogram()


ggplot(Training_dataframe, aes(x = DEMCODE)) +
  geom_bar(mapping = aes(y= ..prop..))

#ggplot2.histogram(data=Training_dataframe, xName='DEMCODE', scale='density')

hist(Training_dataframe$DEMCODE)

hist(Training_dataframe$AGREE) #From this it can be seen that it is bimodal

ggplot(data = Training_dataframe, mapping = aes(x= DEMCODE, y= AGREE)) +
  geom_point() #NOTICE THAT THIS IS A TIME PROGRESSION, SO I NEED ONE THAT WILL TAKE INTO ACCOUNT BYCOND, DEMCODE


ggplot(data = Training_dataframe, mapping = aes(x= DEMCODE, y= ANSWER1)) +
  geom_point() #


ggplot(data = Training_dataframe, mapping = aes(x= DEMCODE, y= ANSWER2)) +
  geom_point() #


ggplot(data = Training_dataframe, mapping = aes(x= DEMCODE, y= ANSWER3)) +
  geom_point() #


ggplot(data = Training_dataframe, mapping = aes(x= DEMCODE, y= ANSWER4)) +
  geom_point() #


ggplot(data = Training_dataframe, mapping = aes(x= DEMCODE, y= ANSWER5)) +
  geom_point() #


ggplot(data = Training_dataframe, mapping = aes(x= DEMCODE, y= ANSWER6)) +
  geom_point() #


ggplot(data = Training_dataframe, mapping = aes(x= DEMCODE, y= ANSWER7)) +
  geom_point() #

#THIS IS A GOOD START, BUT I WANT SOMETHING LESS CLUSTERED AND EASIER TO READ, PERHAPS A PIE CHART OR A CIRCLE PLOT


#PERHAPS I NEED TO DO A K-MEANS CLASSIFICATION FOR THIS 



# I ALSO WANT ONE THAT SHOWS THE PROGRESSION OF RESPONSES OVER THE YEARS OF 2020, 2019, 2018





data_ISED$AGREE == data_ISED$MOST_NEGATIVE_OR_LEAST_POSITIVE

ggplot(data = data_ISED, mapping = aes(x= AGREE, y= MOST_NEGATIVE_OR_LEAST_POSITIVE)) +
  geom_point()




```